packages:
  - apps/*
  - packages/*
  - integrators/*
  - e2e
  - documentation

allowBuilds:
  '@nestjs/core': set this to true or false
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  node-jq: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  vue-demi: set this to true or false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - aws-sdk
  - core-js
  - esbuild
  - node-jq
  - protobufjs
  - sharp
  - vue-demi
