packages:
  - apps/*
  - packages/*
  - integrators/*
  - e2e
  - documentation

onlyBuiltDependencies:
  - '@parcel/watcher'
  - aws-sdk
  - core-js
  - esbuild
  - node-jq
  - protobufjs
  - sharp
  - vue-demi
