const BANNER = [
  '# AUTO-GENERATED — DO NOT EDIT',
  '# Generated by `qelos interfaces build --lang py`',
  '# Source: *.blueprint.json files',
].join('\n');

const VALID_PY_IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/;
const PY_RESERVED = new Set([
  'False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break',
  'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally',
  'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal',
  'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield',
]);

export function toPascalCase(value) {
  const cleaned = String(value || '').replace(/[^a-zA-Z0-9]+/g, ' ').trim();
  if (!cleaned) return '_';
  const pascal = cleaned
    .split(/\s+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
  return /^[0-9]/.test(pascal) ? `_${pascal}` : pascal;
}

function mapPrimitive(type) {
  switch (type) {
    case 'number':
      return 'float';
    case 'boolean':
      return 'bool';
    case 'object':
      return 'Dict[str, Any]';
    case 'string':
    case 'date':
    case 'datetime':
    case 'time':
    case 'file':
      return 'str';
    default:
      return 'Any';
  }
}

function isStringLiteralEnum(values) {
  return Array.isArray(values)
    && values.length > 0
    && values.every((value) => typeof value === 'string');
}

function toEnumLiteral(values) {
  return `Literal[${values.map((value) => JSON.stringify(value)).join(', ')}]`;
}

function mapDescriptorToPyType(descriptor) {
  let baseType;

  if (descriptor.enum && isStringLiteralEnum(descriptor.enum)) {
    baseType = toEnumLiteral(descriptor.enum);
  } else {
    baseType = mapPrimitive(descriptor.type);
  }

  if (descriptor.multi) {
    return `List[${baseType}]`;
  }

  return baseType;
}

function safePyKey(key) {
  if (!VALID_PY_IDENTIFIER.test(key) || PY_RESERVED.has(key)) {
    return null;
  }
  return key;
}

function resolvePascalNames(blueprints) {
  const used = new Set();
  const map = new Map();
  for (const blueprint of blueprints) {
    if (!blueprint || !blueprint.identifier) continue;
    const base = toPascalCase(blueprint.identifier);
    let candidate = base;
    let suffix = 2;
    while (used.has(candidate)) {
      candidate = `${base}${suffix}`;
      suffix += 1;
    }
    used.add(candidate);
    map.set(blueprint.identifier, candidate);
  }
  return map;
}

function buildTypedDict(name, blueprint, identifierToPascal) {
  const properties = blueprint.properties && typeof blueprint.properties === 'object'
    ? blueprint.properties
    : {};
  const relations = Array.isArray(blueprint.relations) ? blueprint.relations : [];

  const lines = [];
  const fields = [];

  for (const [key, descriptor] of Object.entries(properties)) {
    if (!descriptor || typeof descriptor !== 'object') continue;
    const safeKey = safePyKey(key);
    if (!safeKey) continue;
    const tsType = mapDescriptorToPyType(descriptor);
    fields.push(`    ${safeKey}: ${tsType}`);
  }

  for (const relation of relations) {
    if (!relation || !relation.key) continue;
    const safeKey = safePyKey(relation.key);
    if (!safeKey) continue;
    const targetPascal = identifierToPascal.get(relation.target);
    const tsType = targetPascal ? `Union["${targetPascal}Entity", str]` : 'str';
    fields.push(`    ${safeKey}: ${tsType}`);
  }

  lines.push(`class ${name}Properties(TypedDict, total=False):`);
  if (fields.length === 0) {
    lines.push('    pass');
  } else {
    lines.push(...fields);
  }

  lines.push('');
  lines.push(`class ${name}Entity(${name}Properties, total=False):`);
  lines.push('    _id: str');
  lines.push('    identifier: str');

  return lines.join('\n');
}

export function generatePyDeclarations(blueprints) {
  const safeBlueprints = Array.isArray(blueprints) ? blueprints.filter((bp) => bp && bp.identifier) : [];
  const identifierToPascal = resolvePascalNames(safeBlueprints);

  const sections = [
    BANNER,
    'from typing import Any, Dict, List, Literal, TypedDict, Union',
  ];

  for (const blueprint of safeBlueprints) {
    const name = identifierToPascal.get(blueprint.identifier);
    sections.push(buildTypedDict(name, blueprint, identifierToPascal));
  }

  return sections.join('\n\n') + '\n';
}

export default generatePyDeclarations;
