const BANNER = [
  '// AUTO-GENERATED — DO NOT EDIT',
  '// Generated by `qelos interfaces build`',
  '// Source: *.blueprint.json files',
].join('\n');

const SDK_IMPORT = "import type { IBaseBlueprintEntity } from '@qelos/sdk/blueprints-entities';";

const VALID_IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

function quoteKey(key) {
  return VALID_IDENTIFIER.test(key) ? key : JSON.stringify(key);
}

export function toPascalCase(value) {
  const cleaned = String(value || '').replace(/[^a-zA-Z0-9]+/g, ' ').trim();
  if (!cleaned) return '_';
  const pascal = cleaned
    .split(/\s+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
  return /^[0-9]/.test(pascal) ? `_${pascal}` : pascal;
}

function mapPrimitive(type) {
  switch (type) {
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'object':
      return 'Record<string, any>';
    case 'string':
    case 'date':
    case 'datetime':
    case 'time':
    case 'file':
      return 'string';
    default:
      return 'any';
  }
}

function isStringLiteralEnum(values) {
  return Array.isArray(values)
    && values.length > 0
    && values.every((value) => typeof value === 'string');
}

function toEnumLiteral(values) {
  return values.map((value) => JSON.stringify(value)).join(' | ');
}

function isUnion(typeString) {
  return typeString.includes('|');
}

function buildSchemaType(schema, depth = 0) {
  if (!schema || typeof schema !== 'object' || depth >= 4) {
    return 'Record<string, any>';
  }

  if (schema.type === 'array') {
    const itemType = buildSchemaType(schema.items, depth + 1);
    return isUnion(itemType) ? `Array<${itemType}>` : `${itemType}[]`;
  }

  if (schema.type === 'object' && schema.properties && typeof schema.properties === 'object') {
    const entries = Object.entries(schema.properties);
    if (entries.length === 0) {
      return 'Record<string, any>';
    }
    const lines = entries.map(([key, propSchema]) => {
      const propType = buildSchemaType(propSchema, depth + 1);
      return `    ${quoteKey(key)}?: ${propType};`;
    });
    return `{\n${lines.join('\n')}\n  }`;
  }

  switch (schema.type) {
    case 'number':
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'string':
      return 'string';
    case 'object':
      return 'Record<string, any>';
    default:
      return 'any';
  }
}

function mapDescriptorToTsType(descriptor) {
  let baseType;

  if (descriptor.enum && isStringLiteralEnum(descriptor.enum)) {
    baseType = toEnumLiteral(descriptor.enum);
  } else if (descriptor.type === 'object' && descriptor.schema) {
    baseType = buildSchemaType(descriptor.schema);
  } else {
    baseType = mapPrimitive(descriptor.type);
  }

  if (descriptor.multi) {
    return isUnion(baseType) ? `Array<${baseType}>` : `${baseType}[]`;
  }

  return baseType;
}

function buildPropertiesInterface(name, blueprint, identifierToPascal) {
  const properties = blueprint.properties && typeof blueprint.properties === 'object'
    ? blueprint.properties
    : {};
  const relations = Array.isArray(blueprint.relations) ? blueprint.relations : [];

  const lines = [`export interface ${name}Properties {`];

  for (const [key, descriptor] of Object.entries(properties)) {
    if (!descriptor || typeof descriptor !== 'object') continue;
    const tsType = mapDescriptorToTsType(descriptor);
    const optional = descriptor.required ? '' : '?';
    lines.push(`  ${quoteKey(key)}${optional}: ${tsType};`);
  }

  for (const relation of relations) {
    if (!relation || !relation.key) continue;
    const targetPascal = identifierToPascal.get(relation.target);
    const tsType = targetPascal
      ? `Pick<${targetPascal}Entity, 'identifier'> | string`
      : 'string';
    lines.push(`  ${quoteKey(relation.key)}?: ${tsType};`);
  }

  lines.push('}');
  return lines.join('\n');
}

function buildEntityInterface(name) {
  return `export interface ${name}Entity extends IBaseBlueprintEntity, ${name}Properties {}`;
}

function resolvePascalNames(blueprints) {
  const used = new Set();
  const map = new Map();
  for (const blueprint of blueprints) {
    if (!blueprint || !blueprint.identifier) continue;
    const base = toPascalCase(blueprint.identifier);
    let candidate = base;
    let suffix = 2;
    while (used.has(candidate)) {
      candidate = `${base}${suffix}`;
      suffix += 1;
    }
    used.add(candidate);
    map.set(blueprint.identifier, candidate);
  }
  return map;
}

function buildRegistry(blueprints, identifierToPascal) {
  const lines = ['export interface BlueprintEntitiesRegistry {'];
  for (const blueprint of blueprints) {
    const pascal = identifierToPascal.get(blueprint.identifier);
    if (!pascal) continue;
    lines.push(`  ${JSON.stringify(blueprint.identifier)}: ${pascal}Entity;`);
  }
  lines.push('}');
  return lines.join('\n');
}

function buildSdkAugmentation(blueprints, identifierToPascal) {
  const lines = [
    "declare module '@qelos/sdk' {",
    '  interface BlueprintEntitiesRegistry {',
  ];
  for (const blueprint of blueprints) {
    const pascal = identifierToPascal.get(blueprint.identifier);
    if (!pascal) continue;
    lines.push(`    ${JSON.stringify(blueprint.identifier)}: ${pascal}Entity;`);
  }
  lines.push('  }');
  lines.push('}');
  return lines.join('\n');
}

export function generateTsDeclarations(blueprints) {
  const safeBlueprints = Array.isArray(blueprints) ? blueprints.filter((bp) => bp && bp.identifier) : [];
  const identifierToPascal = resolvePascalNames(safeBlueprints);

  const sections = [BANNER, SDK_IMPORT];

  for (const blueprint of safeBlueprints) {
    const name = identifierToPascal.get(blueprint.identifier);
    sections.push(buildPropertiesInterface(name, blueprint, identifierToPascal));
    sections.push(buildEntityInterface(name));
  }

  sections.push(buildRegistry(safeBlueprints, identifierToPascal));
  sections.push(buildSdkAugmentation(safeBlueprints, identifierToPascal));

  return sections.join('\n\n') + '\n';
}

export default generateTsDeclarations;
